
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { store } from '@/store/';
import { Provider } from "react-redux";

import StateProvider from "@/components/provider/StateProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StateProvider>

      <body className={inter.className}>{children}</body>
      </StateProvider>
    </html>
  );
}